# Generated by Django 3.2.25 on 2025-02-25 09:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialpoint',
            name='location',
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=4326),
        ),
    ]
